name: Update Blog Posts

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  
on:
  push:
      branches:
        - main
  schedule:
    - cron: '0 6 * * *'  # 매일 19시에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        git config --global user.name 'duwlsssss'
        git config --global user.email 'rladuwls0814@gmail.com'
        git push https://${{ secrets.GH_PAT }}@github.com/duwlsssss/JoyVelog.git

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py